# k8s-manifests/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: harness-demo-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: harness-demo-app
  template:
    metadata:
      labels:
        app: harness-demo-app
    spec:
      containers:
      - name: harness-demo-app
        image: ganesh243/harness-demo-app:1.0.0 # This will be managed by Harness CI/CD
        ports:
        - containerPort: 8080